import type { SignalDevelopmentStage, StageCapabilities } from './signalDevelopmentTypes'

const CAPABILITIES_BY_STAGE: Record<SignalDevelopmentStage, StageCapabilities> = {
  1: {
    canDetectAssemblies: false,
    canUseTeacher: false,
    canSelfRecall: false,
    canLearnContrast: false,
    canTrackSequence: false,
    canSelectActions: false,
    canPredictHierarchically: false,
    canReconsolidate: false,
    canModulateLearning: false,
    canExportCandidates: false,
  },
  2: {
    canDetectAssemblies: true,
    canUseTeacher: false,
    canSelfRecall: false,
    canLearnContrast: false,
    canTrackSequence: false,
    canSelectActions: false,
    canPredictHierarchically: false,
    canReconsolidate: false,
    canModulateLearning: false,
    canExportCandidates: false,
  },
  3: {
    canDetectAssemblies: true,
    canUseTeacher: true,
    canSelfRecall: false,
    canLearnContrast: false,
    canTrackSequence: false,
    canSelectActions: false,
    canPredictHierarchically: false,
    canReconsolidate: false,
    canModulateLearning: false,
    canExportCandidates: false,
  },
  4: {
    canDetectAssemblies: true,
    canUseTeacher: true,
    canSelfRecall: true,
    canLearnContrast: false,
    canTrackSequence: false,
    canSelectActions: false,
    canPredictHierarchically: false,
    canReconsolidate: false,
    canModulateLearning: true,
    canExportCandidates: false,
  },
  5: {
    canDetectAssemblies: true,
    canUseTeacher: true,
    canSelfRecall: true,
    canLearnContrast: true,
    canTrackSequence: false,
    canSelectActions: false,
    canPredictHierarchically: false,
    canReconsolidate: true,
    canModulateLearning: true,
    canExportCandidates: false,
  },
  6: {
    canDetectAssemblies: true,
    canUseTeacher: true,
    canSelfRecall: true,
    canLearnContrast: true,
    canTrackSequence: true,
    canSelectActions: false,
    canPredictHierarchically: true,
    canReconsolidate: true,
    canModulateLearning: true,
    canExportCandidates: false,
  },
  7: {
    canDetectAssemblies: true,
    canUseTeacher: true,
    canSelfRecall: true,
    canLearnContrast: true,
    canTrackSequence: true,
    canSelectActions: true,
    canPredictHierarchically: true,
    canReconsolidate: true,
    canModulateLearning: true,
    canExportCandidates: false,
  },
  8: {
    canDetectAssemblies: true,
    canUseTeacher: true,
    canSelfRecall: true,
    canLearnContrast: true,
    canTrackSequence: true,
    canSelectActions: true,
    canPredictHierarchically: true,
    canReconsolidate: true,
    canModulateLearning: true,
    canExportCandidates: true,
  },
}

export function getStageCapabilities(stage: SignalDevelopmentStage): StageCapabilities {
  return CAPABILITIES_BY_STAGE[stage]
}
