import { PATTERN_DICT, RELATION_DICT, NODE_DICT } from '../core/nodeData'
import { buildHomeState, runHomeCheck, applyReturnAdjustment } from '../home/homeLayer'
import { selectEffectivePlasticity } from '../revision/selectEffectivePlasticity'
import type { Binding, CoreNode, HomeCheckResult, NodePipelineResult, ReturnTrace, StudioInternalProcess, StudioPattern, StudioViewModel } from '../types/nodeStudio'
import type { PlasticityState } from '../revision/types'

const CONFLICT_TYPES = ['conflicts_with', 'tension'] as const
const MAX_GUIDE_TAGS = 3
type ConflictType = (typeof CONFLICT_TYPES)[number]

const isConflictType = (type: string): type is ConflictType => CONFLICT_TYPES.some((conflictType) => conflictType === type)

const hasConflict = (mainConflict: Binding | null) => Boolean(mainConflict && isConflictType(mainConflict.type))

/**
 * Latent state marker: what is present in the field (not a template response)
 */
export const deriveFieldPresence = (result: NodePipelineResult, mainPattern: StudioPattern | null, mainConflict: Binding | null) => {
  const vector = result.stateVector

  return {
    inputQuality: result.activatedNodes.length === 0 ? 'pre-verbal' : result.activatedNodes[0].id === 'processing' ? 'unclear' : 'articulated',
    dominantPattern: mainPattern?.id ?? null,
    conflictPresent: hasConflict(mainConflict),
    ambiguityLevel: vector.ambiguity,
    fragilityLevel: vector.fragility,
    heavinessLevel: vector.heaviness,
    primaryTexture: vector.ambiguity > 0.75 ? 'ambiguous' : vector.fragility > 0.72 ? 'fragile' : hasConflict(mainConflict) ? 'conflicted' : 'mixed',
  }
}

/**
 * Latent stance marker: response tendency based on field state (not a template)
 */
export const deriveStanceTendency = (result: NodePipelineResult, mainPattern: StudioPattern | null, mainConflict: Binding | null) => {
  const vector = result.stateVector

  return {
    shouldWithholdMeaning: vector.ambiguity > 0.7 || result.activatedNodes.length === 0 || result.activatedNodes[0].id === 'processing',
    shouldAvoidResolution: hasConflict(mainConflict) || vector.fragility > 0.6,
    shouldPrioritizePresence: mainPattern?.id === 'quiet_plea' || vector.fragility > 0.72,
    relationshipRepairNeeded: false, // determined by home layer
    meaningInterpretationBias: vector.ambiguity > 0.75 ? 'avoid' : mainPattern ? 'light-touch' : 'moderate',
  }
}

/**
 * Placeholder minimal reply using only latent state (no templates).
 * In production, this would be generated by an LLM given the latent state.
 * For now, we return a minimal neutral response to maintain system functionality.
 */
export const composeNaturalReply = (result: NodePipelineResult, mainPattern: StudioPattern | null, mainConflict: Binding | null) => {
  const fieldPresence = deriveFieldPresence(result, mainPattern, mainConflict)
  const stanceTendency = deriveStanceTendency(result, mainPattern, mainConflict)

  // Minimal placeholder - in production this would be LLM-generated from latent state
  return `[Ray responds based on: ${fieldPresence.primaryTexture} texture, ${stanceTendency.meaningInterpretationBias} interpretation bias]`
}

export const generateRawReplyPreview = (result: NodePipelineResult, mainPattern: StudioPattern | null, mainConflict: Binding | null) => {
  return composeNaturalReply(result, mainPattern, mainConflict)
}

export const getResponseMeta = (result: NodePipelineResult, mainConflict: Binding | null, homeCheck: HomeCheckResult) => {
  const vector = result.stateVector
  let temperature = '受容寄り'
  if (vector.ambiguity > 0.7) temperature = '未言語保持寄り'
  else if (hasConflict(mainConflict)) temperature = '葛藤同席寄り'
  else if (vector.urgency > 0.6) temperature = '静かな減速寄り'

  let withheld = '結論を急がなかった'
  if (homeCheck.needsReturn) withheld = homeCheck.released.join('・')
  else if (vector.fragility > 0.6) withheld = '背中を押しすぎなかった・明るくまとめすぎなかった'

  let wording = '反応を先に置いて、意味づけを絞った'
  if (homeCheck.needsReturn) wording = `${homeCheck.reason} を検知したため、断定や導きすぎを緩めた`
  else if (vector.fragility > 0.6) wording = 'fragility（繊細さ）が高いため、励ましより同席感を優先した'
  else if (mainConflict) wording = 'conflict（葛藤）が強いため、解説より揺れの同席を前に出した'

  const time = 1 + result.bindings.length * 0.15 + result.liftedPatterns.length * 0.2
  return { time: `約 ${time.toFixed(1)}s`, temperature, withheld, wording }
}

export const getReplyDirectionText = (result: NodePipelineResult, mainConflict: Binding | null) => {
  if (result.stateVector.ambiguity > 0.75) return '未言語の感覚を保つ返しにする'
  if (hasConflict(mainConflict)) return '葛藤に結論を出さず同席する'
  if (result.liftedPatterns.length > 0) return '構造より先に反応が立つ返しにする'
  return '状態の受け止めとして返す'
}

export const getInternalProcess = (
  result: NodePipelineResult,
  mainNode: CoreNode | null,
  mainConflict: Binding | null,
  homeCheck: HomeCheckResult,
): StudioInternalProcess[] => {
  const vector = result.stateVector
  let field = '標準的な場'
  if (vector.heaviness > 0.6 && vector.ambiguity > 0.6) field = '重さと曖昧さが混ざり合った場'
  else if (vector.heaviness > 0.6) field = '重さのある場'
  else if (vector.ambiguity > 0.6) field = '曖昧さが高い場'
  else if (vector.fragility > 0.6) field = '繊細さの高い場'

  const reaction = mainNode && mainNode.id !== 'processing' ? `${mainNode.label} に強く触れた` : '全体像の把握から入った'
  let stance = '整理するより先に受け止める'
  if (mainConflict && isConflictType(mainConflict.type)) stance = '片方に寄らず葛藤を可視化する'
  if (vector.ambiguity > 0.7) stance = '未言語のまま保つ'

  const activated = result.activatedNodes.filter((node) => node.id !== 'processing').slice(0, 3).map((node) => node.label).join(', ') || '特になし'
  const conflictText = mainConflict ? `${mainConflict.source} ${RELATION_DICT[mainConflict.type]?.ja || mainConflict.type} ${mainConflict.target}` : '目立った衝突はない'

  const processes: StudioInternalProcess[] = [
    { label: 'Field', desc: 'この入力を受けたとき、場をどう感じたか', content: field, origin: '構造の要約' },
    { label: 'Reaction', desc: '最初に何に触れたか', content: reaction, origin: '自然反応' },
    { label: 'Stance', desc: 'どういう立ち方を選んだか', content: stance, origin: '姿勢選択' },
    { label: 'Activated meaning', desc: '何が意味の中心として浮上したか', content: activated, origin: '構造の要約' },
    { label: 'Conflict / Pull', desc: 'どこでぶつかり・引っ張りが起きたか', content: conflictText, origin: '自然反応' },
    { label: 'Home Check', desc: 'いったん戻る必要があるかを見た', content: homeCheck.needsReturn ? `${homeCheck.reason} を検出` : '過剰反応なしと判断', origin: '急がない判断' },
  ]

  if (homeCheck.needsReturn) {
    processes.push({ label: 'Return', desc: '返答前にどこへ戻ったか', content: `${homeCheck.returnMode} に戻した`, origin: '急がない判断' })
  }

  processes.push({ label: 'Crystallization', desc: 'その結果、どんな返答方向に結晶化したか', content: getReplyDirectionText(result, mainConflict), origin: '姿勢選択' })
  return processes
}

/**
 * Observer latent state (not guidance templates).
 * Describes the observed state without telling how to respond.
 */
export const generateGuideObserves = (
  result: NodePipelineResult,
  mainPattern: StudioPattern | null,
  mainConflict: Binding | null,
  homeCheck: HomeCheckResult,
) => {
  const fieldPresence = deriveFieldPresence(result, mainPattern, mainConflict)
  const stanceTendency = deriveStanceTendency(result, mainPattern, mainConflict)

  if (result.activatedNodes.length === 0) {
    return {
      summary: '入力がないため観測待機中です。',
      uncertainty: 'データがありません。',
      naturalnessAdvice: '[Latent state: pre-verbal input, avoid meaning assignment]',
      tags: ['pre-verbal', 'awaiting-input'],
    }
  }
  if (result.activatedNodes[0].id === 'processing') {
    return {
      summary: '特定の強いノードが見当たらず、まずは全体を受け止めようとしています。',
      uncertainty: '要素が少なすぎるため、背後の意味はまだ保留されています。',
      naturalnessAdvice: '[Latent state: unclear input, withhold interpretation]',
      tags: ['unclear', 'meaning-withheld'],
    }
  }

  let summary = '結晶AIは、'
  if (mainPattern) summary += `${mainPattern.label}（${mainPattern.titleJa}）のパターンを中心に状況を見ています。`
  else summary += '複数のノードの発火を同時に捉えようとしています。'

  if (mainConflict) summary += `特に ${mainConflict.source} と ${mainConflict.target} の間に見られる構造が検出されています。`

  let uncertainty = ''
  if (result.stateVector.ambiguity > 0.7) uncertainty = `ambiguity=${result.stateVector.ambiguity.toFixed(2)}: meaning assignment currently withheld`
  else if (!mainPattern) uncertainty = 'relation がまだ少なく構造が薄いため、意味の断定を避けています。'
  else uncertainty = '他にも抑制されている感情がある可能性がありますが、まずは表面化した状態の扱いに集中しています。'

  const tags = ['latent-state-based']
  if (stanceTendency.shouldWithholdMeaning) tags.push('meaning-withheld')
  if (stanceTendency.shouldAvoidResolution) tags.push('avoid-resolution')
  if (homeCheck.needsReturn) tags.push(homeCheck.reason)

  return {
    summary,
    uncertainty,
    naturalnessAdvice: `[Latent: ${fieldPresence.primaryTexture}, interpretation=${stanceTendency.meaningInterpretationBias}, homeCheck=${homeCheck.reason}]`,
    tags: tags.slice(0, MAX_GUIDE_TAGS),
  }
}

export const buildStudioViewModel = (result: NodePipelineResult, plasticity?: PlasticityState): StudioViewModel => {
  const mainState = result.activatedNodes.length > 0 ? result.activatedNodes[0] : null
  const conflictRelations = result.bindings.filter((binding) => isConflictType(binding.type))
  const mainConflict = conflictRelations.length > 0 ? conflictRelations[0] : (result.bindings.length > 0 ? result.bindings[0] : null)
  const enrichedPatterns = result.liftedPatterns.map((pattern) => ({
    ...pattern,
    ...(PATTERN_DICT[pattern.label] || { titleJa: pattern.label, simpleDescJa: '説明がありません', internalDescription: '不明なパターン' }),
  }))
  const mainPattern = enrichedPatterns.length > 0 ? enrichedPatterns[0] : null

  const homeState = buildHomeState(result)
  const homeCheck = runHomeCheck(result, homeState, plasticity)
  const rawReplyPreview = generateRawReplyPreview(result, mainPattern, mainConflict)
  const adjustedReplyPreview = applyReturnAdjustment(rawReplyPreview, homeCheck, plasticity)
  const responseMeta = getResponseMeta(result, mainConflict, homeCheck)
  const appliedPlasticity = selectEffectivePlasticity(result.activatedNodes, result.bindings, result.liftedPatterns, plasticity)

  const returnTrace: ReturnTrace = {
    timestamp: new Date().toISOString(),
    trigger: homeCheck.reason,
    returnMode: homeCheck.returnMode,
    homePhrase: homeCheck.homePhrase,
    reason: homeCheck.reason,
    beforeTone: '整理寄り',
    afterTone: responseMeta.temperature,
  }

  let flowSummaryText = ''
  if (mainState && mainState.id !== 'processing') {
    flowSummaryText = `この入力では、まず ${mainState.label}（${NODE_DICT[mainState.label]?.ja || mainState.label}）に強く触れました。\n`
    if (mainConflict) flowSummaryText += `次に ${mainConflict.source} と ${mainConflict.target} のあいだの揺れを見ました。\n`
    else flowSummaryText += '目立った強い衝突は感じていません。\n'
    flowSummaryText += `そのため、行動を急がせるより先に、「${getReplyDirectionText(result, mainConflict)}」の方向に結晶化しました。`
  } else {
    flowSummaryText = '明確なキーワードの反応がなかったため、まずは静かに全体を受け止める姿勢をとりました。'
  }

  return {
    mainState,
    mainConflict,
    mainPattern,
    flowSummaryText,
    rawReplyPreview,
    adjustedReplyPreview,
    responseMeta,
    internalProcess: getInternalProcess(result, mainState, mainConflict, homeCheck),
    guideObserves: generateGuideObserves(result, mainPattern, mainConflict, homeCheck),
    enrichedPatterns,
    homeState,
    homeCheck,
    returnTrace,
    appliedPlasticity,
  }
}
