import type { LexicalState } from '../lexical/types'
import type { MicroSignalState } from './packetTypes'
import type { PhrasePlan, ProtoMeaning, SentencePlan, SentenceTone, SignalDecision } from './types'

/**
 * Resolve latent tone based on proto-meanings and utterance mode.
 * This is a perceptual marker, not a template instruction.
 */
const resolveTone = (protoMeanings: ProtoMeaning[], utteranceMode: SignalDecision['utteranceMode']): SentenceTone => {
  if (utteranceMode === 'boundary') return 'holding'
  if (utteranceMode === 'resonant') return 'opening'
  const hasAmbiguous = protoMeanings.some((pm) => pm.texture === 'ambiguous' || pm.texture === 'still')
  if (hasAmbiguous) return 'still'
  return 'searching'
}

/**
 * Build sentence plan from phrase candidates and latent state.
 * REMOVED: All hardcoded template sentences.
 * The actual utterance should be generated by an LLM given the latent state.
 */
export const buildSignalSentencePlan = (
  phrases: PhrasePlan[],
  protoMeanings: ProtoMeaning[],
  decision: SignalDecision,
  context?: {
    lexicalState?: LexicalState
    microSignalState?: MicroSignalState
  },
): SentencePlan => {
  // Use phrase candidates if available, otherwise placeholder
  const lead = phrases[0]?.phrase ?? '[latent: awaiting phrase generation]'
  const body = phrases.slice(1, 3).map((p) => p.phrase)

  // Latent markers (not templates) - in production these would inform LLM generation
  const lexicalState = context?.lexicalState
  const microSignalState = context?.microSignalState

  let close = '[latent: closure based on ' + decision.utteranceMode + ']'

  // Latent state adjustments based on field conditions
  if (microSignalState?.fieldTone === 'low-band') {
    close = '[latent: heaviness present, avoid rushing]'
  } else if (
    microSignalState?.fieldTone === 'high-band'
    && (lexicalState?.requestType === 'advice' || lexicalState?.requestType === 'choice')
    && lexicalState.optionLabels?.[0]
  ) {
    close = decision.optionUtteranceHints?.suggestedClose ?? `[latent: openness present, option ${lexicalState.optionLabels[0]} foregrounded]`
  }

  const tone = resolveTone(protoMeanings, decision.utteranceMode)

  return { lead, body: body.slice(0, 3), close, tone }
}
